sudo: required

language: go

go_import_path: github.com/bosh-prometheus/cf_exporter

services:
  - docker

env:
  matrix:
    - DOCKER_IMAGE_NAME=boshprometheus/cf-exporter
  global:
    - secure: tVKemB1hVkeST+gTHPRM5StRAVjYBxCOxr1pbPJUVC5m4FwhIZCptSwxfJmAt9sxTY8MVzQyMgvhTqGt/YWZEyp2xhy3Pz9+sBLgDEq375a45Th/BozdwEqISiym0Fo0oSRaigVv15jgq4WcT+mWhQQjh7qiJwTafByunY/QjgdloLfzyVy8sm54gM3X7pZJsw8jatL/U5Zl+HVDmTGGN5pCeom+Rz6Z+FNOYEGBK6TGM3pxrAGnepVGlEnXLsT6q1ZVJiQs6NJCeJWy2cSbD4TchEp5s7HgQhGgzV6aiPKRtTbyIVYImjC0uwzum74cEzN9tnDCm+ldjQ245pVvlIukSjgsG13FiRKPiKpQ9YyHccjNnTv0vOTCdWF2F6cgZEkGFB8KvAa3VjlrQuKFuL+rKGSyo9oXECk1prBEfQ8As5vG1p8UbpytJ/KcDLXUzhwSaKUR3vfh9dnLGJprnJ99fUNN7be5B+95e0gWKo/3BumvcZziYPzGAMKVkcs7Pv7Dad5G46ZRrrLY6uHIhVr/N8GzXlz5ZA7t45tPECBa1mPPVYq9smRmG9j4ASms9EP6kgrSBwu+qAGy7C63wXD8Sk4R+8CwhlOIvq5UvGc94O1jnf/VPQDW9Z98B33kaDbqy6RpfjAcsL2I+q9gEeZWR3kWGPOGfBPk2jP6CU4=
    - secure: uYhP1w6LV1KNSYpAKAsfBswjEhI/YUY5LVzCNQG991GoyUC1kU8rPv85wAMRAaOZBv6dcD/kY3aU01K94Xq6hvQZZjbrSFds47SUPv8X4FEDAwn1I5Q95FVHottjEp8TM93fCmCG2dBVm4/CV8KsYYYufIuAFBRcYNJd6ubAIPBIsh5ZkaXa0uQnpQvI8DrgEm3abGS5urjVdqCmdKjNIilX8tamKb53LOmq2PKtbRrAlhx5L1PaaATbCLOPGVqBnuSqSBacquo7FXrjWdmcLcl8VXq/GsMLOaeBkffsHhszCTXl+jqtPMRaeQnYX2p2B0suiliqloz9WcG5GGYZ4SodpPYN5eqQ5tdExvxdxHDPs67hkoV9abhYGTVy1tM27sZjU6V/Pvo8BMkEwl2Tl63A36+SKHrzQ6NCwcc7lDouMNHlzzqo2ZW3OR9x2BXwe5SGy5OmgYa3zsUbh30YaZvUTekwk87U+dBLV1bEq74AxieyI9/+4M4Bc8mclsGpag9nbui5RSUB+PVP+lN2CH+3NTZzixgtpx6PJBSHJLrU1r8ZbdPTFHeqdKWpS+FbAx2UJUzCwO9pQ8NCT/mib6kw4fUdo25MJ7c3Oz4pdtfM3EBkj0LeMbozqUDznL2Nm8DfI3zvDDO1dNEhSHSgD/eG7lctnNXXo8ocK9wokc4=

jobs:
  include:
    - stage: tests
      script: make test
    - stage: docker image
      script:
        - make crossbuild
        - ln -s .build/linux-amd64/cf_exporter cf_exporter
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
          fi
        - |
          if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
          fi
        - docker images
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE_NAME
          fi
